version: '3.8'

# Due to using mongo atlas cloud no need to add service for it

# docker-compose --env-file <path-to env file> up -d --build

services:

  nginx:
    depends_on:
      - server
      - client
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
      

    networks:
      - app-net



# server does envirmonet checking at server.js code
  server:
    build: 
      context: ./Server/
      dockerfile: Dockerfile.backend
      args:
        - NODE_ENV=${NODE_ENV:-development}
    container_name: ems_server

    ports:
      - 5500:5500

    networks:
      - app-net




# client has to be provided with enviroment or by default it will build development env
  client:
    build: 
      context: ./ems/
      dockerfile: Dockerfile.frontend
      target: ${NODE_ENV:-development}
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: ems_client

    ports:
      - 3000:3000

    networks:
      - app-net 




networks:
  app-net :
    driver : bridge




