# ── EMS Deployments ──────────────────────────────────────────────────────────

---
# EMS Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-server-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: ems-server
spec:
  replicas: {{ .Values.deployments.ems.replicas.ems_server_replicas}} 
  selector:
    matchLabels:
      app: {{ .Values.deployments.ems.labels.ems_server_label}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.ems.labels.ems_server_label}}
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: app-secrets
          secret:
            secretName: prod-ems-server-config
      containers:
      - name: ems-server
        image: {{ .Values.images.ems.images.ems_server_image}}
        volumeMounts:
        - name: app-secrets
          mountPath: /run/secrets
          readOnly: true
        ports:
        - containerPort: {{ .Values.images.ems.ports.ems_server_container_port}}
        resources:
          requests:
            memory: "110Mi"   # 165Mi / 1.5

          limits:
            memory: "165Mi"

        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "db-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "ems_db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MYSQL_ROOT_PASSWORD

---
# EMS Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-client-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: ems-client
spec:
  replicas: {{ .Values.deployments.ems.replicas.ems_client_replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployments.ems.labels.ems_client_label}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.ems.labels.ems_client_label}}
    spec:
      containers:
      - name: ems-client
        image: {{ .Values.images.ems.images.ems_client_image}}
        ports:
        - containerPort: {{ .Values.images.ems.ports.ems_client_container_port}}
        resources:
          requests:
            memory: "170Mi"   # 255Mi 

          limits:
            memory: "255Mi"


# ── Hospital Deployments ──────────────────────────────────────────────────────

---
# Hospital Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-server-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: hospital-server
spec:
  replicas: {{ .Values.deployments.hospital.replicas.hospital_server_replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployments.hospital.labels.hospital_server_label}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.hospital.labels.hospital_server_label}}
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: app-secrets
          secret:
            secretName: prod-hospital-server-config
      containers:
      - name: hospital-server
        image: {{ .Values.images.hospital.images.hospital_server_image}}
        volumeMounts:
        - name: app-secrets
          mountPath: /run/secrets
          readOnly: true
        ports:
        - containerPort: {{ .Values.images.hospital.ports.hospital_server_container_port}}
        resources:
          requests:
            memory: "183Mi"   # 275Mi / 1.5
  
          limits:
            memory: "275Mi"
            
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "db-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "ems_db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MYSQL_ROOT_PASSWORD

---
# Hospital Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-client-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: hospital-client
spec:
  replicas: {{ .Values.deployments.hospital.replicas.hospital_client_replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployments.hospital.labels.hospital_client_label}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.hospital.labels.hospital_client_label}}
    spec:
      containers:
      - name: hospital-client
        image: {{ .Values.images.hospital.images.hospital_client_image}}
        ports:
        - containerPort: {{ .Values.images.hospital.ports.hospital_client_container_port}}
        resources:
          requests:
            memory: "228Mi"   # 342Mi / 1.5
  
          limits:
            memory: "342Mi"


# ── Storage Deployments ──────────────────────────────────────────────────────────

---
# Storage Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-server-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: storage-server
spec:
  replicas: {{ .Values.deployments.storage.replicas.storage_server_replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployments.storage.labels.storage_server_label}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.storage.labels.storage_server_label}}
    spec:
      automountServiceAccountToken: false
      volumes:
      - name: app-secrets
        secret:
          secretName: prod-storage-server-config
      containers:
      - name: storage-server
        image: {{ .Values.images.storage.images.storage_server_image}}
        imagePullPolicy: Always
        volumeMounts:
        - name: app-secrets
          mountPath: /run/secrets
          readOnly: true
        ports:
        - containerPort: {{ .Values.images.storage.ports.storage_server_container_port}}
        resources:
          requests:
            memory: "147Mi"   # 220Mi / 1.5

          limits:
            memory: "220Mi"

        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "db-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "ems_db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MYSQL_ROOT_PASSWORD

---
# Storage Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-client-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: storage-client
spec:
  replicas: {{ .Values.deployments.storage.replicas.storage_client_replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployments.storage.labels.storage_client_label}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.storage.labels.storage_client_label}}
    spec:
      containers:
      - name: storage-client
        image: {{ .Values.images.storage.images.storage_client_image}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.images.storage.ports.storage_client_container_port}}
        resources:
          requests:
            memory: "200Mi"   # 300Mi / 1.5

          limits:
            memory: "300Mi"


# ── DB Deployment ──────────────────────────────────────────────────────────

---
# Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: db
spec:
  replicas: {{ .Values.deployments.db.replicas.db_replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployments.db.labels.db_label}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.db.labels.db_label}}
    spec:
      containers:
      - name: db
        image: {{ .Values.images.db.images.db_image}}
        ports:
        - containerPort: {{ .Values.images.db.ports.db_container_port}}
        resources:
          requests:
            memory: "600Mi"

          limits:
            memory: "930Mi"

        env:
        - name: MYSQL_DATABASE
          value: "ems_db"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MYSQL_ROOT_PASSWORD

# ── Nginx Deployment ──────────────────────────────────────────────────────────

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.deployments.nginx.replicas.nginx_replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployments.nginx.labels.nginx_label}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.nginx.labels.nginx_label}}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.images.nginx.images.nginx_image}}
        ports:
        - containerPort: {{ .Values.services.nginx.ems_nginx_port}}
        - containerPort: {{ .Values.services.nginx.hospital_nginx_port}}
        resources:
          requests:
            memory: "32Mi"    # nginx is very lightweight

          limits:
            memory: "48Mi"

        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx-conf-file
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-configmap