services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      mode: global
      resources:
        limits:
          memory: 256M
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
    - target: 9090
      published: 9090
      protocol: tcp
      mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml   # Path inside container
    networks:
      - monitoring

# app services should be on the same network to allow Prometheus to scrape cAdvisor metrics
# we will manually connect the app services to the monitoring network in their respective docker-compose files
networks:
  monitoring: 
    name: monitoring
    external: true
    driver: overlay

configs:
  prometheus_config:
    external: true