# ports in production = compose ports + 200

services:

  nginx:
    restart: on-failure
    image: baraamohamed/gradproj:nginx_swarm
    ports:
      - target: 3050
        published: 3250
        protocol: tcp
        mode: ingress
      - target: 3051
        published: 3251
        protocol: tcp
        mode: ingress
      - target: 3052
        published: 3252
        protocol: tcp
        mode: ingress
    networks:
      - ems-net
      - hospital-net
      - storage-net

  # ems services:
  ################## 
  ems_server:
    image: baraamohamed/gradproj:ems-server-${EMS_SERVER_VERSION:-latest}
    deploy:
      replicas: 3

    environment:
      NODE_ENV: production
    ports:
      - target: 5500
        protocol: tcp
        mode: ingress
    networks:
      - ems-net
      - db-net

    secrets:
      - prod_ems_server_config

  ems_client:
    image: baraamohamed/gradproj:ems-client-${EMS_CLIENT_VERSION:-latest}
    deploy:
      replicas: 3

    ports:
      - target: 3000
        protocol: tcp
        mode: ingress
    networks:
      - ems-net


  # hospital services:
  ################## 
  hospital_server:
    image: baraamohamed/gradproj:hospital-server-${HOSPITAL_SERVER_VERSION:-latest}
    deploy:
      replicas: 3

    environment:
      NODE_ENV: production
    ports:
      - target: 8888
        protocol: tcp
        mode: ingress
    networks:
      - hospital-net
      - db-net

    secrets:
      - prod_hospital_server_config


  hospital_client:
    image: baraamohamed/gradproj:hospital-client-${HOSPITAL_CLIENT_VERSION:-latest}
    deploy:
      replicas: 3

    ports:
      - target: 3000
        protocol: tcp
        mode: ingress
    networks:
      - hospital-net



 # storage services:
 ################## 

  storage_client:
    image: baraamohamed/gradproj:storage-client-${STORAGE_CLIENT_VERSION:-latest}
    deploy:
      replicas: 3

    ports:
      - target: 3000
        protocol: tcp
        mode: ingress
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - storage-net



  storage_server:
    image: baraamohamed/gradproj:storage-server-${STORAGE_SERVER_VERSION:-latest}
    deploy:
      replicas: 3

    ports:
      - target: 5000
        protocol: tcp
        mode: ingress
    environment:
      NODE_ENV: ${NODE_ENV}
    secrets:
      - prod_storage_server_config

    networks:
      - storage-net
      - db-net






  # db services:
  ################## 

  mysql_db:
    image: mysql:8
    deploy:
      replicas: 1

    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD  
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD 
      MYSQL_USER: appuser 
    volumes:
      - db_data:/var/lib/mysql
    configs:
    - source: mysql_init_sql
      target: /docker-entrypoint-initdb.d/init.sql
    networks:
      - db-net

volumes:
  db_data:
    name: db_data

configs:
  mysql_init_sql:
    external: true

networks:
  ems-net:
    driver: overlay
  hospital-net:
    driver: overlay
  db-net:
    driver: overlay
  storage-net:
    driver: overlay


secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
  MYSQL_PASSWORD:
    external: true
  prod_hospital_server_config:
    external: true
  prod_ems_server_config:
    external: true
  prod_storage_server_config:
    external: true
