services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      mode: global
      resources:
        limits:
          memory: 256M
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - target: 8080
        published: 8088
        protocol: tcp
        mode: ingress
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.role == manager  # Must be on manager — needs stable storage
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    user: root # Prometheus needs root to read the Docker socket
    ports:
    - target: 9090
      published: 9090
      protocol: tcp
      mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml   # Path inside container
    networks:
      - monitoring

# app services should be on the same network to allow Prometheus to scrape cAdvisor metrics
# we will manually connect the app services to the monitoring network in their respective docker-compose files
networks:
  monitoring: 
    driver: overlay

configs:
  prometheus_config:
    external: true
    
volumes:
  grafana-data: