# PORTS in staging are different from production to avoid conflict between them if they are on the same host staging_ports = production_ports + 100 

services:

  nginx:
    restart: on-failure
    image: baraamohamed/gradproj:nginx_swarm
    ports:
      - target: 3050
        published: 3150
        protocol: tcp
        mode: ingress
      - target: 3051
        published: 3151
        protocol: tcp
        mode: ingress
      - target: 3052
        published: 3152
        protocol: tcp
        mode: ingress
    networks:
      - ems-net
      - hospital-net
      - storage-net

  # ems services:
  ################## 
  ems_server:
    image: baraamohamed/gradproj:ems-server-${EMS_SERVER_VERSION:-latest}
    deploy:
      replicas: 2
    environment:
      NODE_ENV: production
    ports:
      - target: 5500
        protocol: tcp
        mode: ingress
    networks:
      - ems-net
      - db-net

    secrets:
      - prod_ems_server_config

  
  ems_client:
    image: baraamohamed/gradproj:ems-client-${EMS_CLIENT_VERSION:-latest}
    deploy:
      replicas: 2
    ports:
      - target: 3000
        protocol: tcp
        mode: ingress
    networks:
      - ems-net


  # hospital services:
  ################## 
  hospital_server:
    image: baraamohamed/gradproj:hospital-server-${HOSPITAL_SERVER_VERSION:-latest}
    deploy:
      replicas: 2
    environment:
      NODE_ENV: production
    ports:
      - target: 8888
        protocol: tcp
        mode: ingress
    networks:
      - hospital-net
      - db-net

    secrets:
      - prod_hospital_server_config
      

  hospital_client:
    image: baraamohamed/gradproj:hospital-client-${HOSPITAL_CLIENT_VERSION:-latest}
    deploy:
      replicas: 2
    ports:
      - target: 3000
        protocol: tcp
        mode: ingress
    networks:
      - hospital-net

  
  # storage services:
  ################## 
  storage_server:
    image: baraamohamed/gradproj:storage-server-${STORAGE_SERVER_VERSION:-latest}
    environment:
      NODE_ENV: ${NODE_ENV}
    deploy:
      replicas: 2
    ports:
      - target: 5000
        protocol: tcp
        mode: ingress

    networks:
      - storage-net
      - db-net

    secrets:
      - prod_storage_server_config


  storage_client:
    image: baraamohamed/gradproj:storage-client-${STORAGE_CLIENT_VERSION:-latest}
    deploy:
      replicas: 2
    ports:
      - target: 3000
        protocol: tcp
        mode: ingress
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - storage-net




  # db services:
  ################## 
  mysql_db:
    image: mysql:8
    deploy:
      replicas: 1
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD  
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD 
      MYSQL_USER: appuser 
    volumes:
      - db_data:/var/lib/mysql
    configs:
    - source: mysql_init_schema
      target: /docker-entrypoint-initdb.d/1_init.sql
    - source: mysql_init_seed
      target: /docker-entrypoint-initdb.d/2_insertions.sql
    networks:
      - db-net
      

volumes:
  db_data:
    name: db_data 

configs:
  mysql_init_schema:
    external: true
  mysql_init_seed:
    external: true

networks:
  ems-net:
    driver: overlay
  hospital-net:
    driver: overlay
  db-net:
    driver: overlay
  storage-net:
    driver: overlay




secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
  MYSQL_PASSWORD:
    external: true
  prod_hospital_server_config:
    external: true
  prod_ems_server_config:
    external: true
  prod_storage_server_config:
    external: true
