
# EMS containers & Hospital containers are separated by different networks
# EMS and Hospital servers are connected to the same database network to access centralized database
services:

# So host can resolve services names "ems_server" & "ems_client" 
  nginx:
    restart: on-failure
    image: baraamohamed/gradproj:nginx
    ports:
      - "3050:3050"
      - "3051:3051"
      

    networks:
      - ems-net
      - hospital-net


# server does envirmonet checking at server.js code
  ems_server:
    image: baraamohamed/gradproj:ems-server-1.0.0
    container_name: ems_server

    networks:
      - ems-net
      - db-net




# client has to be provided with enviroment or by default it will build development env
  ems_client:
    image: baraamohamed/gradproj:ems-client-1.0.0
    container_name: ems_client


    networks:
      - ems-net

  # server does envirmonet checking at server.js code
  hospital_server:
    image: baraamohamed/gradproj:hospital-server-1.0.0
    container_name: hospital_server



    networks:
      - hospital-net
      - db-net




# client has to be provided with enviroment or by default it will build development env
  hospital_client:
    image: baraamohamed/gradproj:hospital-client-1.0.0
    container_name: hospital_client
    ports:
      - 3001:3000

    networks:
      - hospital-net
      

  mysql_db:
    image: baraamohamed/gradproj:db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: cenralized_mysql


    networks:
      - db-net




networks:
  ems-net :
    driver : bridge
  hospital-net :
    driver : bridge
  db-net :
    driver : bridge




