FROM node:20-alpine

WORKDIR /app

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN echo "Building in $NODE_ENV mode"

# Required for native Node modules (bcrypt, sharp, etc.)
RUN apk add --no-cache python3 make g++

COPY package.json package-lock.json ./
RUN npm ci

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

COPY . .

EXPOSE 5500
CMD ["npm","run","start"]
