apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: production
type: Opaque   # generic secret type
data:
  # Values must be base64-encoded
  MYSQL_ROOT_PASSWORD: MDEwMDA3MjY4MDZaWGN2

---

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: staging
type: Opaque   # generic secret type
data:
  # Values must be base64-encoded
  MYSQL_ROOT_PASSWORD: MDEwMDA3MjY4MDZaWGN2

