apiVersion: v1
entries:
  app-chart:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-26T12:14:37.573883007+03:00"
    description: A Helm chart for Kubernetes Hospital and Management APPs
    digest: 1f19bf08b9a982eb75cf539b05de7687204806a5032272279d1db976b6e3fb52
    name: app-chart
    type: application
    urls:
    - https://github.com/BaraaMohamed2311/Helm-Charts.git/app-chart-0.1.0.tgz
    version: 0.1.0
generated: "2026-05-26T12:14:37.573343954+03:00"
