FROM node:20-alpine

WORKDIR /app

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN echo "Building in $NODE_ENV mode"

# 👇 REQUIRED for native Node addons (bcrypt)
RUN apk add --no-cache python3 make g++

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 8888
CMD ["npm","run","start"]
