- name: Detect changed services
  id: detect
  shell: bash
  run: |
    services=()

    files="${{ steps.changes.outputs.all_changed_files }}"

    [[ $files == *"Websites/ems/client"* ]] && services+=("ems-client")
    [[ $files == *"Websites/ems/server"* ]] && services+=("ems-server")
    [[ $files == *"Websites/hospital/client"* ]] && services+=("hospital-client")
    [[ $files == *"Websites/hospital/server"* ]] && services+=("hospital-server")

    joined=$(IFS=,; echo "${services[*]}")
    echo "services=$joined" >> "$GITHUB_OUTPUT"