name: Trigger Jenkins
if: steps.detect.outputs.services != ''
uses: appleboy/jenkins-action@v1
with:
  url: ${{ secrets.JENKINS_URL }}
  user: ${{ secrets.JENKINS_USER }}
  token: ${{ secrets.JENKINS_TOKEN }}
  job: image_building
  params: |
    SERVICES=${{ steps.detect.outputs.services }}